import { XMLBuilder, XMLParser } from "fast-xml-parser";
import { colorIndex } from "../scripts/color_index.ts";
import { BpyTheme, xml_builder_config, strong_edit, xml_parser_config } from "./utils.ts";

const hexReplace = (_key?: string, value?: string) => {
  if (typeof(value) !== 'string') return
  const transformed_value = value.toUpperCase()
  if (colorIndex[transformed_value]) {
    return colorIndex[transformed_value];
  }
  return value;
};

function transform_xml_to_whiskers(xml: BpyTheme, version: string): string {
  const hex_replaced_jso = strong_edit(xml, hexReplace);

  const builder = new XMLBuilder(xml_builder_config);
  const xml_content = builder.build(hex_replaced_jso);
  
  const whiskers_front_matter = `
---
whiskers:
  version: "^2.5.1"
  matrix:
    - flavor
    - accent
  filename: "themes-${version}/{{flavor.identifier}}/Catppuccin {{ flavor.identifier | capitalize }} {{ accent | capitalize }}.xml"
  hex_format: "#{{R}}{{G}}{{B}}{{A}}"
---
  
{#- This file is autogenerated by build-tera.ts, do not edit it manually -#}
`;

  return whiskers_front_matter + xml_content;
}

async function build_for_version(version: string): Promise<void> {
  const reference = await Deno.readTextFile(`./versions/${version}.xml`);

  const parser = new XMLParser(xml_parser_config);
  const xml: BpyTheme = parser.parse(reference, true);

  
  const tera_content = transform_xml_to_whiskers(xml, version);
  // [TODO]: Hacky...
  const tera_content_transformed = tera_content.replace(/&quot;/g, '"');
  await Deno.writeTextFile(`./${version}.tera`, tera_content_transformed);
}

build_for_version("4.5LTS");
build_for_version("5.0.0");
