import { XMLBuilder, XMLParser } from "fast-xml-parser";
import { colorIndex } from "../scripts/color_index.ts";
import {
  BpyTheme,
  strong_edit,
  xml_builder_config,
  xml_parser_config,
} from "./utils.ts";

const hexReplace = (_key?: string, value?: string) => {
  if (typeof value !== "string") return;
  const transformed_value = value.toUpperCase();
  if (colorIndex[transformed_value]) {
    return colorIndex[transformed_value];
  }
  return value;
};

function transform_xml_to_whiskers(xml: BpyTheme, version: string): string {
  const hex_replaced_jso = strong_edit(xml.bpy.Theme, hexReplace);

  const themeStyle = xml.bpy.ThemeStyle
  for (const [key, value] of Object.entries(themeStyle)) {
    value.ThemeFontStyle["@_shadow"] = `{{${key}_shadow}}`
  }

  const builder = new XMLBuilder(xml_builder_config);
  const xml_content = builder.build({
    bpy: {
      Theme: hex_replaced_jso,
      ThemeStyle: themeStyle,
    },
  });

  const whiskers_front_matter = `
---
whiskers:
  version: "^2.5.1"
  matrix:
    - flavor
    - accent
  filename: "themes-${version}/{{flavor.identifier}}/Catppuccin {{ flavor.identifier | capitalize }} {{ accent | capitalize }}.xml"
  hex_format: "#{{R}}{{G}}{{B}}{{A}}"
---
  
{#- This file is autogenerated by build-tera.ts, do not edit it manually -#}

{%- set panel_title_shadow = if(cond=flavor.dark, t=3, f=0) -%}
{%- set widget_shadow = if(cond=flavor.dark, t=1, f=0) -%}
{%- set tooltip_shadow = if(cond=flavor.dark, t=1, f=0) -%}

{#- Used by 3.5.x -#}
{%- set widget_label_shadow = if(cond=flavor.dark, t=3, f=0) -%}

{%- set active_object = peach -%}
{%- set object_select = maroon -%}

{%- set outliner_select = blue -%}

{%- set uv_select = peach -%}
{%- set edge_select = peach -%}

{%- set mesh_bevel = blue -%}
{%- set mesh_seam = red -%}
{%- set mesh_sharp = teal -%}
{%- set mesh_crease = pink -%}
{%- set mesh_freestyle = green | mod(opacity=0.3) -%}

{%- set axis_x = red -%}
{%- set axis_y = green -%}
{%- set axis_z = blue -%}
{%- set axis_w = yellow -%}

{%- set accent = flavor.colors[accent] -%}

`;

  return whiskers_front_matter + xml_content;
}

async function build_for_version(version: string): Promise<void> {
  const reference = await Deno.readTextFile(`./versions/${version}.xml`);

  const parser = new XMLParser(xml_parser_config);
  const xml: BpyTheme = parser.parse(reference, true);

  const tera_content = transform_xml_to_whiskers(xml, version);
  // [TODO]: Hacky...
  const tera_content_transformed = tera_content.replace(/&quot;/g, '"');
  await Deno.writeTextFile(`./${version}.tera`, tera_content_transformed);
}

build_for_version("4.5LTS");
build_for_version("5.0.0");
build_for_version("3.5.1");
build_for_version("2.83LTS");
